name = "cyvian-website"
type = "webpack"
account_id = "pablomh15@pm.me"
workers_dev = true
route = "cyvianchile.com/*"
zone_id = "edef019782b9906e16525f225d956f5b"

[site]
bucket = "./public"
entry-point = "workers-site"