backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"
publish_mode: editorial_workflow
locale: "es"

collections:
  - name: "ajustes"
    label: "Ajustes del sitio"
    files:
      - file: "data/navigation.json"
        label: "Navegación principal"
        name: "navigation"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Etiqueta", name: "label", widget: "string" }
              - { label: "URL", name: "href", widget: "string" }
